/* Generated by gen.rb CommunityEngine Inc. 2000-2005 */
#ifndef _SSPROTO_SV_H_
#define _SSPROTO_SV_H_
#include "vce.h"

#undef SSPROTO_TEST_INT
#define SSPROTO_TEST_INT 10
#undef SSPROTO_TEST_STR
#define SSPROTO_TEST_STR "test"
#undef SSPROTO_USERID_SIZE_MAX
#define SSPROTO_USERID_SIZE_MAX 32
#undef SSPROTO_OK
#define SSPROTO_OK 0
#undef SSPROTO_E_FILE_NAME_INVALID
#define SSPROTO_E_FILE_NAME_INVALID -1
#undef SSPROTO_E_FILE_NAME_TOO_LONG
#define SSPROTO_E_FILE_NAME_TOO_LONG -2
#undef SSPROTO_E_FILE_ACCESS
#define SSPROTO_E_FILE_ACCESS -3
#undef SSPROTO_E_KVS_COMMAND
#define SSPROTO_E_KVS_COMMAND -10
#undef SSPROTO_E_KVS_ARRAY_NOT_IMPLEMENTED
#define SSPROTO_E_KVS_ARRAY_NOT_IMPLEMENTED -11
#undef SSPROTO_E_CHANNEL_FULL
#define SSPROTO_E_CHANNEL_FULL -30
#undef SSPROTO_E_CHANNEL_JOIN_REQUIRED
#define SSPROTO_E_CHANNEL_JOIN_REQUIRED -31
#undef SSPROTO_E_CANT_LOCK
#define SSPROTO_E_CANT_LOCK -40
#undef SSPROTO_E_CANT_UNLOCK
#define SSPROTO_E_CANT_UNLOCK -41
#undef SSPROTO_E_IMAGE_STORE_CANNOT_ALLOCATE
#define SSPROTO_E_IMAGE_STORE_CANNOT_ALLOCATE -42
#undef SSPROTO_E_IMAGE_INVALID_SIZE
#define SSPROTO_E_IMAGE_INVALID_SIZE -43
#undef SSPROTO_E_IMAGE_NOT_FOUND
#define SSPROTO_E_IMAGE_NOT_FOUND -44
#undef SSPROTO_E_IMAGE_CANNOT_CONVERT
#define SSPROTO_E_IMAGE_CANNOT_CONVERT -45
#undef SSPROTO_E_PROJECT_NOT_SHARED
#define SSPROTO_E_PROJECT_NOT_SHARED -46
#undef SSPROTO_FILE_PATH_MAX
#define SSPROTO_FILE_PATH_MAX 64
#undef SSPROTO_FILE_SIZE_MAX
#define SSPROTO_FILE_SIZE_MAX 131072
#undef SSPROTO_FILE_SIZE_ABS_MAX
#define SSPROTO_FILE_SIZE_ABS_MAX 1048576
#undef SSPROTO_FILE_EXIST
#define SSPROTO_FILE_EXIST 1
#undef SSPROTO_FILE_NOT_EXIST
#define SSPROTO_FILE_NOT_EXIST 0
#undef SSPROTO_IMAGE_WIDTH_MAX
#define SSPROTO_IMAGE_WIDTH_MAX 2048
#undef SSPROTO_IMAGE_HEIGHT_MAX
#define SSPROTO_IMAGE_HEIGHT_MAX 2048
#undef SSPROTO_IMAGE_PART_WIDTH_MAX
#define SSPROTO_IMAGE_PART_WIDTH_MAX 32
#undef SSPROTO_IMAGE_PART_HEIGHT_MAX
#define SSPROTO_IMAGE_PART_HEIGHT_MAX 32
#undef SSPROTO_PNG_SIZE_MAX
#define SSPROTO_PNG_SIZE_MAX 1048576
#undef SSPROTO_RAW_IMAGE_SIZE_MAX
#define SSPROTO_RAW_IMAGE_SIZE_MAX 1048576
#undef SSPROTO_GENERATE_ID_NUM_MAX
#define SSPROTO_GENERATE_ID_NUM_MAX 100
#undef SSPROTO_KVS_COMMAND_MAX
#define SSPROTO_KVS_COMMAND_MAX 1024
#undef SSPROTO_KVS_ELEMENT_MAX
#define SSPROTO_KVS_ELEMENT_MAX 1024
#undef SSPROTO_KVS_ARRAYLEN_MAX
#define SSPROTO_KVS_ARRAYLEN_MAX 1024
#undef SSPROTO_KVS_VALUE_STRING
#define SSPROTO_KVS_VALUE_STRING 1
#undef SSPROTO_KVS_VALUE_ARRAY
#define SSPROTO_KVS_VALUE_ARRAY 2
#undef SSPROTO_KVS_VALUE_INTEGER
#define SSPROTO_KVS_VALUE_INTEGER 3
#undef SSPROTO_KVS_VALUE_NIL
#define SSPROTO_KVS_VALUE_NIL 4
#undef SSPROTO_KVS_VALUE_ERROR
#define SSPROTO_KVS_VALUE_ERROR 6
#undef SSPROTO_KVS_KEY_MAX
#define SSPROTO_KVS_KEY_MAX 128
#undef SSPROTO_KVS_FIELD_MAX
#define SSPROTO_KVS_FIELD_MAX 128
#undef SSPROTO_KVS_BIN_MAX
#define SSPROTO_KVS_BIN_MAX 262144
#undef SSPROTO_SHARE_MAX
#define SSPROTO_SHARE_MAX 128
#undef SSPROTO_SEARCH_MAX
#define SSPROTO_SEARCH_MAX 20
#undef SSPROTO_PROJECT_IS_NOT_SHARED
#define SSPROTO_PROJECT_IS_NOT_SHARED 0
#undef SSPROTO_PROJECT_IS_SHARED
#define SSPROTO_PROJECT_IS_SHARED 1
#undef SSPROTO_PROJECT_IS_PUBLISHED
#define SSPROTO_PROJECT_IS_PUBLISHED 2
#undef SSPROTO_PRESENCE_PER_PROJECT_MAX
#define SSPROTO_PRESENCE_PER_PROJECT_MAX 1024
#undef SSPROTO_PACKET_SIZE_MAX
#define SSPROTO_PACKET_SIZE_MAX 65536

#ifndef _SSPROTO_AAA_ENUMDEF_
#define _SSPROTO_AAA_ENUMDEF_
typedef enum {
 SSPROTO_AAA_OK = 0,
 SSPROTO_AAA_NG = 1,

} SSPROTO_AAA;
#endif

#ifndef _SSPROTO_FUNCID_ENUMDEF_
#define _SSPROTO_FUNCID_ENUMDEF_
typedef enum _SSPROTO_FUNCID{
  SSPROTO_C2S_PING=1,
  SSPROTO_C2S_CONN_SERIAL=10,
  SSPROTO_C2S_CLEAN_ALL=12,
  SSPROTO_C2S_PUT_FILE=20,
  SSPROTO_C2S_GET_FILE=30,
  SSPROTO_C2S_CHECK_FILE=40,
  SSPROTO_C2S_ENSURE_IMAGE=50,
  SSPROTO_C2S_UPDATE_IMAGE_PART=52,
  SSPROTO_C2S_GET_IMAGE_PNG=54,
  SSPROTO_C2S_GET_IMAGE_RAW=56,
  SSPROTO_C2S_GENERATE_ID_32=100,
  SSPROTO_C2S_KVS_COMMAND_STR=120,
  SSPROTO_C2S_KVS_COMMAND_STR_ONEWAY=122,
  SSPROTO_C2S_KVS_PUSH_TO_LIST=130,
  SSPROTO_C2S_KVS_GET_LIST_RANGE=132,
  SSPROTO_C2S_KVS_APPEND_STRING_ARRAY=134,
  SSPROTO_C2S_KVS_GET_STRING_ARRAY=136,
  SSPROTO_C2S_KVS_SAVE_BIN=140,
  SSPROTO_C2S_KVS_LOAD_BIN=150,
  SSPROTO_C2S_COUNTER_ADD=160,
  SSPROTO_C2S_COUNTER_GET=161,
  SSPROTO_C2S_SHARE_PROJECT=180,
  SSPROTO_C2S_PUBLISH_PROJECT=182,
  SSPROTO_C2S_SEARCH_SHARED_PROJECTS=186,
  SSPROTO_C2S_SEARCH_PUBLISHED_PROJECTS=188,
  SSPROTO_C2S_PROJECT_IS_JOINABLE=190,
  SSPROTO_C2S_UNSHARE_PROJECT=192,
  SSPROTO_C2S_UNPUBLISH_PROJECT=194,
  SSPROTO_C2S_IS_PUBLISHED_PROJECT=196,
  SSPROTO_C2S_IS_SHARED_PROJECT=198,
  SSPROTO_C2S_UPDATE_PRESENCE=200,
  SSPROTO_C2S_DELETE_PRESENCE=201,
  SSPROTO_C2S_LIST_PRESENCE=204,
  SSPROTO_C2S_COUNT_PRESENCE=206,
  SSPROTO_C2S_LOCK_GRID=210,
  SSPROTO_C2S_UNLOCK_GRID=212,
  SSPROTO_C2S_LOCK_KEEP_GRID=214,
  SSPROTO_C2S_LOCK_PROJECT=216,
  SSPROTO_C2S_UNLOCK_PROJECT=218,
  SSPROTO_C2S_LOCK_KEEP_PROJECT=220,
  SSPROTO_C2S_BROADCAST=230,
  SSPROTO_C2S_CHANNELCAST=232,
  SSPROTO_C2S_JOIN_CHANNEL=234,
  SSPROTO_C2S_LEAVE_CHANNEL=236,
  SSPROTO_C2S_NEARCAST=240,
  SSPROTO_C2S_UPDATE_NEARCAST_POSITION=242,
  SSPROTO_C2S_GET_CHANNEL_MEMBER_COUNT=244,
  SSPROTO_S2C_PONG=2,
  SSPROTO_S2C_VERSION_NOTIFY=4,
  SSPROTO_S2C_CONN_SERIAL_RESULT=11,
  SSPROTO_S2C_CLEAN_ALL_RESULT=13,
  SSPROTO_S2C_PUT_FILE_RESULT=21,
  SSPROTO_S2C_GET_FILE_RESULT=31,
  SSPROTO_S2C_CHECK_FILE_RESULT=41,
  SSPROTO_S2C_ENSURE_IMAGE_RESULT=51,
  SSPROTO_S2C_UPDATE_IMAGE_PART_RESULT=53,
  SSPROTO_S2C_GET_IMAGE_PNG_RESULT=55,
  SSPROTO_S2C_GET_IMAGE_RAW_RESULT=57,
  SSPROTO_S2C_GENERATE_ID_32_RESULT=101,
  SSPROTO_S2C_KVS_COMMAND_STR_RESULT=121,
  SSPROTO_S2C_KVS_PUSH_TO_LIST_RESULT=131,
  SSPROTO_S2C_KVS_GET_LIST_RANGE_RESULT=133,
  SSPROTO_S2C_KVS_APPEND_STRING_ARRAY_RESULT=135,
  SSPROTO_S2C_KVS_GET_STRING_ARRAY_RESULT=137,
  SSPROTO_S2C_KVS_SAVE_BIN_RESULT=141,
  SSPROTO_S2C_KVS_LOAD_BIN_RESULT=151,
  SSPROTO_S2C_COUNTER_GET_RESULT=162,
  SSPROTO_S2C_SHARE_PROJECT_RESULT=181,
  SSPROTO_S2C_PUBLISH_PROJECT_RESULT=183,
  SSPROTO_S2C_SEARCH_SHARED_PROJECTS_RESULT=187,
  SSPROTO_S2C_SEARCH_PUBLISHED_PROJECTS_RESULT=189,
  SSPROTO_S2C_PROJECT_IS_JOINABLE_RESULT=191,
  SSPROTO_S2C_IS_PUBLISHED_PROJECT_RESULT=197,
  SSPROTO_S2C_IS_SHARED_PROJECT_RESULT=199,
  SSPROTO_S2C_LIST_PRESENCE_RESULT=205,
  SSPROTO_S2C_COUNT_PRESENCE_RESULT=207,
  SSPROTO_S2C_LOCK_GRID_RESULT=211,
  SSPROTO_S2C_UNLOCK_GRID_RESULT=213,
  SSPROTO_S2C_LOCK_PROJECT_RESULT=217,
  SSPROTO_S2C_UNLOCK_PROJECT_RESULT=219,
  SSPROTO_S2C_BROADCAST_NOTIFY=231,
  SSPROTO_S2C_CHANNELCAST_NOTIFY=233,
  SSPROTO_S2C_JOIN_CHANNEL_RESULT=235,
  SSPROTO_S2C_LEAVE_CHANNEL_RESULT=237,
  SSPROTO_S2C_NEARCAST_NOTIFY=241,
  SSPROTO_S2C_GET_CHANNEL_MEMBER_COUNT_RESULT=245,
  SSPROTO_IDMAX=256
} SSPROTO_FUNCID;
#endif

typedef struct _ssproto_teststruct {
    int x;
    int y;
} ssproto_teststruct;


#ifdef __cplusplus
extern "C" {
#endif

#define SSPROTO_MAX_RECV_RECORD_LENGTH 262421
#define SSPROTO_MAX_CONNECTION 1024

int ssproto_new(conn_t c);
int ssproto_del(conn_t c);
int ssproto_toomany_recv_warning( conn_t c,int proto_id);
int ssproto_toolong_recv_warning( conn_t c,int proto_id,int length);

int ssproto_sv_pcallback( conn_t c,char *data,int len );
int ssproto_sv_recv_error_callback( conn_t c,int e );

double ssproto_get_ping_recv_count( void );
double ssproto_get_conn_serial_recv_count( void );
double ssproto_get_clean_all_recv_count( void );
double ssproto_get_put_file_recv_count( void );
double ssproto_get_get_file_recv_count( void );
double ssproto_get_check_file_recv_count( void );
double ssproto_get_ensure_image_recv_count( void );
double ssproto_get_update_image_part_recv_count( void );
double ssproto_get_get_image_png_recv_count( void );
double ssproto_get_get_image_raw_recv_count( void );
double ssproto_get_generate_id_32_recv_count( void );
double ssproto_get_kvs_command_str_recv_count( void );
double ssproto_get_kvs_command_str_oneway_recv_count( void );
double ssproto_get_kvs_push_to_list_recv_count( void );
double ssproto_get_kvs_get_list_range_recv_count( void );
double ssproto_get_kvs_append_string_array_recv_count( void );
double ssproto_get_kvs_get_string_array_recv_count( void );
double ssproto_get_kvs_save_bin_recv_count( void );
double ssproto_get_kvs_load_bin_recv_count( void );
double ssproto_get_counter_add_recv_count( void );
double ssproto_get_counter_get_recv_count( void );
double ssproto_get_share_project_recv_count( void );
double ssproto_get_publish_project_recv_count( void );
double ssproto_get_search_shared_projects_recv_count( void );
double ssproto_get_search_published_projects_recv_count( void );
double ssproto_get_project_is_joinable_recv_count( void );
double ssproto_get_unshare_project_recv_count( void );
double ssproto_get_unpublish_project_recv_count( void );
double ssproto_get_is_published_project_recv_count( void );
double ssproto_get_is_shared_project_recv_count( void );
double ssproto_get_update_presence_recv_count( void );
double ssproto_get_delete_presence_recv_count( void );
double ssproto_get_list_presence_recv_count( void );
double ssproto_get_count_presence_recv_count( void );
double ssproto_get_lock_grid_recv_count( void );
double ssproto_get_unlock_grid_recv_count( void );
double ssproto_get_lock_keep_grid_recv_count( void );
double ssproto_get_lock_project_recv_count( void );
double ssproto_get_unlock_project_recv_count( void );
double ssproto_get_lock_keep_project_recv_count( void );
double ssproto_get_broadcast_recv_count( void );
double ssproto_get_channelcast_recv_count( void );
double ssproto_get_join_channel_recv_count( void );
double ssproto_get_leave_channel_recv_count( void );
double ssproto_get_nearcast_recv_count( void );
double ssproto_get_update_nearcast_position_recv_count( void );
double ssproto_get_get_channel_member_count_recv_count( void );
double ssproto_get_pong_send_count( void );
double ssproto_get_version_notify_send_count( void );
double ssproto_get_conn_serial_result_send_count( void );
double ssproto_get_clean_all_result_send_count( void );
double ssproto_get_put_file_result_send_count( void );
double ssproto_get_get_file_result_send_count( void );
double ssproto_get_check_file_result_send_count( void );
double ssproto_get_ensure_image_result_send_count( void );
double ssproto_get_update_image_part_result_send_count( void );
double ssproto_get_get_image_png_result_send_count( void );
double ssproto_get_get_image_raw_result_send_count( void );
double ssproto_get_generate_id_32_result_send_count( void );
double ssproto_get_kvs_command_str_result_send_count( void );
double ssproto_get_kvs_push_to_list_result_send_count( void );
double ssproto_get_kvs_get_list_range_result_send_count( void );
double ssproto_get_kvs_append_string_array_result_send_count( void );
double ssproto_get_kvs_get_string_array_result_send_count( void );
double ssproto_get_kvs_save_bin_result_send_count( void );
double ssproto_get_kvs_load_bin_result_send_count( void );
double ssproto_get_counter_get_result_send_count( void );
double ssproto_get_share_project_result_send_count( void );
double ssproto_get_publish_project_result_send_count( void );
double ssproto_get_search_shared_projects_result_send_count( void );
double ssproto_get_search_published_projects_result_send_count( void );
double ssproto_get_project_is_joinable_result_send_count( void );
double ssproto_get_is_published_project_result_send_count( void );
double ssproto_get_is_shared_project_result_send_count( void );
double ssproto_get_list_presence_result_send_count( void );
double ssproto_get_count_presence_result_send_count( void );
double ssproto_get_lock_grid_result_send_count( void );
double ssproto_get_unlock_grid_result_send_count( void );
double ssproto_get_lock_project_result_send_count( void );
double ssproto_get_unlock_project_result_send_count( void );
double ssproto_get_broadcast_notify_send_count( void );
double ssproto_get_channelcast_notify_send_count( void );
double ssproto_get_join_channel_result_send_count( void );
double ssproto_get_leave_channel_result_send_count( void );
double ssproto_get_nearcast_notify_send_count( void );
double ssproto_get_get_channel_member_count_result_send_count( void );

#ifdef GEN_DEBUG_PRINT

void ssproto_ping_recv_debugprint(int on_off);
void ssproto_conn_serial_recv_debugprint(int on_off);
void ssproto_clean_all_recv_debugprint(int on_off);
void ssproto_put_file_recv_debugprint(int on_off);
void ssproto_get_file_recv_debugprint(int on_off);
void ssproto_check_file_recv_debugprint(int on_off);
void ssproto_ensure_image_recv_debugprint(int on_off);
void ssproto_update_image_part_recv_debugprint(int on_off);
void ssproto_get_image_png_recv_debugprint(int on_off);
void ssproto_get_image_raw_recv_debugprint(int on_off);
void ssproto_generate_id_32_recv_debugprint(int on_off);
void ssproto_kvs_command_str_recv_debugprint(int on_off);
void ssproto_kvs_command_str_oneway_recv_debugprint(int on_off);
void ssproto_kvs_push_to_list_recv_debugprint(int on_off);
void ssproto_kvs_get_list_range_recv_debugprint(int on_off);
void ssproto_kvs_append_string_array_recv_debugprint(int on_off);
void ssproto_kvs_get_string_array_recv_debugprint(int on_off);
void ssproto_kvs_save_bin_recv_debugprint(int on_off);
void ssproto_kvs_load_bin_recv_debugprint(int on_off);
void ssproto_counter_add_recv_debugprint(int on_off);
void ssproto_counter_get_recv_debugprint(int on_off);
void ssproto_share_project_recv_debugprint(int on_off);
void ssproto_publish_project_recv_debugprint(int on_off);
void ssproto_search_shared_projects_recv_debugprint(int on_off);
void ssproto_search_published_projects_recv_debugprint(int on_off);
void ssproto_project_is_joinable_recv_debugprint(int on_off);
void ssproto_unshare_project_recv_debugprint(int on_off);
void ssproto_unpublish_project_recv_debugprint(int on_off);
void ssproto_is_published_project_recv_debugprint(int on_off);
void ssproto_is_shared_project_recv_debugprint(int on_off);
void ssproto_update_presence_recv_debugprint(int on_off);
void ssproto_delete_presence_recv_debugprint(int on_off);
void ssproto_list_presence_recv_debugprint(int on_off);
void ssproto_count_presence_recv_debugprint(int on_off);
void ssproto_lock_grid_recv_debugprint(int on_off);
void ssproto_unlock_grid_recv_debugprint(int on_off);
void ssproto_lock_keep_grid_recv_debugprint(int on_off);
void ssproto_lock_project_recv_debugprint(int on_off);
void ssproto_unlock_project_recv_debugprint(int on_off);
void ssproto_lock_keep_project_recv_debugprint(int on_off);
void ssproto_broadcast_recv_debugprint(int on_off);
void ssproto_channelcast_recv_debugprint(int on_off);
void ssproto_join_channel_recv_debugprint(int on_off);
void ssproto_leave_channel_recv_debugprint(int on_off);
void ssproto_nearcast_recv_debugprint(int on_off);
void ssproto_update_nearcast_position_recv_debugprint(int on_off);
void ssproto_get_channel_member_count_recv_debugprint(int on_off);
void ssproto_pong_send_debugprint(int on_off);
void ssproto_version_notify_send_debugprint(int on_off);
void ssproto_conn_serial_result_send_debugprint(int on_off);
void ssproto_clean_all_result_send_debugprint(int on_off);
void ssproto_put_file_result_send_debugprint(int on_off);
void ssproto_get_file_result_send_debugprint(int on_off);
void ssproto_check_file_result_send_debugprint(int on_off);
void ssproto_ensure_image_result_send_debugprint(int on_off);
void ssproto_update_image_part_result_send_debugprint(int on_off);
void ssproto_get_image_png_result_send_debugprint(int on_off);
void ssproto_get_image_raw_result_send_debugprint(int on_off);
void ssproto_generate_id_32_result_send_debugprint(int on_off);
void ssproto_kvs_command_str_result_send_debugprint(int on_off);
void ssproto_kvs_push_to_list_result_send_debugprint(int on_off);
void ssproto_kvs_get_list_range_result_send_debugprint(int on_off);
void ssproto_kvs_append_string_array_result_send_debugprint(int on_off);
void ssproto_kvs_get_string_array_result_send_debugprint(int on_off);
void ssproto_kvs_save_bin_result_send_debugprint(int on_off);
void ssproto_kvs_load_bin_result_send_debugprint(int on_off);
void ssproto_counter_get_result_send_debugprint(int on_off);
void ssproto_share_project_result_send_debugprint(int on_off);
void ssproto_publish_project_result_send_debugprint(int on_off);
void ssproto_search_shared_projects_result_send_debugprint(int on_off);
void ssproto_search_published_projects_result_send_debugprint(int on_off);
void ssproto_project_is_joinable_result_send_debugprint(int on_off);
void ssproto_is_published_project_result_send_debugprint(int on_off);
void ssproto_is_shared_project_result_send_debugprint(int on_off);
void ssproto_list_presence_result_send_debugprint(int on_off);
void ssproto_count_presence_result_send_debugprint(int on_off);
void ssproto_lock_grid_result_send_debugprint(int on_off);
void ssproto_unlock_grid_result_send_debugprint(int on_off);
void ssproto_lock_project_result_send_debugprint(int on_off);
void ssproto_unlock_project_result_send_debugprint(int on_off);
void ssproto_broadcast_notify_send_debugprint(int on_off);
void ssproto_channelcast_notify_send_debugprint(int on_off);
void ssproto_join_channel_result_send_debugprint(int on_off);
void ssproto_leave_channel_result_send_debugprint(int on_off);
void ssproto_nearcast_notify_send_debugprint(int on_off);
void ssproto_get_channel_member_count_result_send_debugprint(int on_off);

#endif

int ssproto_ping_recv( conn_t _c, VCEI64 t_usec, int cmd );
int ssproto_conn_serial_recv( conn_t _c );
int ssproto_clean_all_recv( conn_t _c );
int ssproto_put_file_recv( conn_t _c, int query_id, const char *filename, const char *data, int data_len );
int ssproto_get_file_recv( conn_t _c, int query_id, const char *filename );
int ssproto_check_file_recv( conn_t _c, int query_id, const char *filename );
int ssproto_ensure_image_recv( conn_t _c, int query_id, int image_id, int w, int h );
int ssproto_update_image_part_recv( conn_t _c, int query_id, int image_id, int x0, int y0, int w, int h, const unsigned char *r, int r_len, const unsigned char *g, int g_len, const unsigned char *b, int b_len );
int ssproto_get_image_png_recv( conn_t _c, int query_id, int image_id );
int ssproto_get_image_raw_recv( conn_t _c, int query_id, int image_id, int x0, int y0, int w, int h );
int ssproto_generate_id_32_recv( conn_t _c, int query_id, int num );
int ssproto_kvs_command_str_recv( conn_t _c, int query_id, const char *command );
int ssproto_kvs_command_str_oneway_recv( conn_t _c, const char *command );
int ssproto_kvs_push_to_list_recv( conn_t _c, int query_id, const char *key, const char *s, int trim );
int ssproto_kvs_get_list_range_recv( conn_t _c, int query_id, const char *key, int start_ind, int end_ind );
int ssproto_kvs_append_string_array_recv( conn_t _c, int query_id, const char *key, const char *field, const char *s, int trim );
int ssproto_kvs_get_string_array_recv( conn_t _c, int query_id, const char *key, const char *field );
int ssproto_kvs_save_bin_recv( conn_t _c, int query_id, const char *key, const char *field, const char *data, int data_len );
int ssproto_kvs_load_bin_recv( conn_t _c, int query_id, const char *key, const char *field );
int ssproto_counter_add_recv( conn_t _c, int counter_category, int counter_id, int addvalue );
int ssproto_counter_get_recv( conn_t _c, int counter_category, int counter_id );
int ssproto_share_project_recv( conn_t _c, int user_id, int project_id, const int *with, int with_len );
int ssproto_publish_project_recv( conn_t _c, int user_id, int project_id );
int ssproto_search_shared_projects_recv( conn_t _c, int user_id );
int ssproto_search_published_projects_recv( conn_t _c );
int ssproto_project_is_joinable_recv( conn_t _c, int project_id, int user_id );
int ssproto_unshare_project_recv( conn_t _c, int project_id );
int ssproto_unpublish_project_recv( conn_t _c, int project_id );
int ssproto_is_published_project_recv( conn_t _c, int project_id );
int ssproto_is_shared_project_recv( conn_t _c, int project_id, int owner_uid );
int ssproto_update_presence_recv( conn_t _c, int project_id, int user_id );
int ssproto_delete_presence_recv( conn_t _c, int project_id, int user_id );
int ssproto_list_presence_recv( conn_t _c, int project_id );
int ssproto_count_presence_recv( conn_t _c, int project_id );
int ssproto_lock_grid_recv( conn_t _c, int grid_id, int x, int y );
int ssproto_unlock_grid_recv( conn_t _c, int grid_id, int x, int y );
int ssproto_lock_keep_grid_recv( conn_t _c, int grid_id, int x, int y );
int ssproto_lock_project_recv( conn_t _c, int project_id, int category );
int ssproto_unlock_project_recv( conn_t _c, int project_id, int category );
int ssproto_lock_keep_project_recv( conn_t _c, int project_id, int category );
int ssproto_broadcast_recv( conn_t _c, int type_id, const char *data, int data_len );
int ssproto_channelcast_recv( conn_t _c, int channel_id, int type_id, const char *data, int data_len );
int ssproto_join_channel_recv( conn_t _c, int channel_id );
int ssproto_leave_channel_recv( conn_t _c );
int ssproto_nearcast_recv( conn_t _c, int x, int y, int range, int type_id, const char *data, int data_len );
int ssproto_update_nearcast_position_recv( conn_t _c, int x, int y );
int ssproto_get_channel_member_count_recv( conn_t _c, int channel_id );



int ssproto_pong_send( conn_t _c, VCEI64 t_usec, int cmd );
int ssproto_version_notify_send( conn_t _c, unsigned int maj, unsigned int min );
int ssproto_conn_serial_result_send( conn_t _c, int serial );
int ssproto_clean_all_result_send( conn_t _c );
int ssproto_put_file_result_send( conn_t _c, int query_id, int result, const char *filename );
int ssproto_get_file_result_send( conn_t _c, int query_id, int result, const char *filename, const char *data, int data_len );
int ssproto_check_file_result_send( conn_t _c, int query_id, int result, const char *filename );
int ssproto_ensure_image_result_send( conn_t _c, int query_id, int result, int image_id );
int ssproto_update_image_part_result_send( conn_t _c, int query_id, int result, int image_id );
int ssproto_get_image_png_result_send( conn_t _c, int query_id, int result, int image_id, const char *png_data, int png_data_len );
int ssproto_get_image_raw_result_send( conn_t _c, int query_id, int result, int image_id, int x0, int y0, int w, int h, const char *raw_data, int raw_data_len );
int ssproto_generate_id_32_result_send( conn_t _c, int query_id, int generated_id_start, int num );
int ssproto_kvs_command_str_result_send( conn_t _c, int query_id, int retcode, int valtype, const char * const *result, int result_len );
int ssproto_kvs_push_to_list_result_send( conn_t _c, int query_id, int retcode, const char *key, int updated_num );
int ssproto_kvs_get_list_range_result_send( conn_t _c, int query_id, int retcode, int start_ind, int end_ind, const char *key, const char * const *result, int result_len );
int ssproto_kvs_append_string_array_result_send( conn_t _c, int query_id, int retcode, const char *key, const char *field );
int ssproto_kvs_get_string_array_result_send( conn_t _c, int query_id, int retcode, const char *key, const char *field, const char * const *result, int result_len );
int ssproto_kvs_save_bin_result_send( conn_t _c, int query_id, int retcode, int valtype, const char *key, const char *field );
int ssproto_kvs_load_bin_result_send( conn_t _c, int query_id, int retcode, int has_data, const char *key, const char *field, const char *data, int data_len );
int ssproto_counter_get_result_send( conn_t _c, int counter_category, int counter_id, int result, int curvalue );
int ssproto_share_project_result_send( conn_t _c, int project_id );
int ssproto_publish_project_result_send( conn_t _c, int project_id );
int ssproto_search_shared_projects_result_send( conn_t _c, int user_id, const int *project_ids, int project_ids_len );
int ssproto_search_published_projects_result_send( conn_t _c, const int *project_ids, int project_ids_len );
int ssproto_project_is_joinable_result_send( conn_t _c, int project_id, int user_id, int result );
int ssproto_is_published_project_result_send( conn_t _c, int project_id, int published );
int ssproto_is_shared_project_result_send( conn_t _c, int project_id, int shared );
int ssproto_list_presence_result_send( conn_t _c, int project_id, const int *user_ids, int user_ids_len );
int ssproto_count_presence_result_send( conn_t _c, int project_id, int user_num );
int ssproto_lock_grid_result_send( conn_t _c, int grid_id, int x, int y, int retcode );
int ssproto_unlock_grid_result_send( conn_t _c, int grid_id, int x, int y, int retcode );
int ssproto_lock_project_result_send( conn_t _c, int project_id, int category, int retcode );
int ssproto_unlock_project_result_send( conn_t _c, int project_id, int category, int retcode );
int ssproto_broadcast_notify_send( conn_t _c, int type_id, int sender_cli_id, const char *data, int data_len );
int ssproto_channelcast_notify_send( conn_t _c, int channel_id, int sender_cli_id, int type_id, const char *data, int data_len );
int ssproto_join_channel_result_send( conn_t _c, int channel_id, int retcode );
int ssproto_leave_channel_result_send( conn_t _c, int retcode );
int ssproto_nearcast_notify_send( conn_t _c, int channel_id, int sender_cli_id, int x, int y, int range, int type_id, const char *data, int data_len );
int ssproto_get_channel_member_count_result_send( conn_t _c, int channel_id, int maxnum, int curnum );

unsigned int ssproto_sv_get_version( unsigned int *subv );
int ssproto_sv_sender( conn_t c, char *data, int len );
conn_t  ssproto_sv_get_current_conn( void );
#ifdef __cplusplus
};
#endif
#endif
