#
# Makefile for VCE document
#
# $Revision$
# $Date: 2007-12-05 17:15:22 +0900 (水, 05 12 2007) $
# $Id$
#
#
# Copyright (C) 2000-2006 Community Engine Inc. All rights reserved.
# "PlayStation" is registered trademark and is trademark of Sony Computer 
# Entertainment Inc.
# For more information, please visit our website at www.ce-lab.net.
#


# Set up version number
MAJV=1
MINV=2
RELV=22
VERSTR=$(MAJV)_$(MINV)_$(RELV)

# Set up admin path
ADMIN_PATH=/opt/chiaki/src/admin/docs
ADMIN_SETPATH=../admin

# Out-put programs
PKGDIR=vcedoc-$(VERSTR)
DOCDIR=docs
PS2DOCDIR=ps2docs

# Source code files
DOCGEN=docgen0.rb
COPYDOC=doc
DOCSRC=docgen.conf doc/api/*.txt

COPYRIGHT="Copyright 2000-2007 Community Engine Inc. All rights reserved."


admin_doc : 
	rm -rf $(ADMIN_SETPATH)
	mkdir $(ADMIN_SETPATH)
	cp -R $(ADMIN_PATH) $(ADMIN_SETPATH)/doc
	# 必要でないファイルを消す
	rm $(ADMIN_SETPATH)/doc/ja/*.ai $(ADMIN_SETPATH)/doc/ja/admin_client.html $(ADMIN_SETPATH)/doc/ja/admcli/system_log.png
	find $(ADMIN_SETPATH) -name '.svn' > /tmp/admin_svndirs
	cat /tmp/admin_svndirs | xargs rm -rf 
	rm /tmp/admin_svndirs

docs : $(DOCGEN) $(DOCSRC)
	rm -rf $(DOCDIR)
	mkdir $(DOCDIR)
	ruby $(DOCGEN) doc/api/*.txt
	ruby docfilter.rb ps2 other $(DOCDIR)/*/*.html
	mkdir $(DOCDIR)/ja/admin $(DOCDIR)/en/admin
	ruby -Ku version.rb $(MAJV).$(MINV).$(RELV) $(COPYRIGHT) $(COPYDOC) $(DOCDIR)
	mkdir $(DOCDIR)/images
	cp -r $(COPYDOC)/images/* $(DOCDIR)/images/
	cp $(COPYDOC)/ja/admin/*.gif $(COPYDOC)/ja/admin/*.png $(DOCDIR)/ja/admin/
#	cp $(COPYDOC)/en/admin/*.gif $(COPYDOC)/en/admin/*.png $(DOCDIR)/en/admin/

	mkdir $(DOCDIR)/text
	cp -r $(COPYDOC)/text/*.txt $(DOCDIR)/text/

	cp $(COPYDOC)/vce.css $(DOCDIR)/
#	cp -r $(DOCDIR)/ja/* $(COPYDOC)/ja/
#	cp -r $(DOCDIR)/en/* $(COPYDOC)/en/



ps2doc : $(DOCGEN) $(DOCSRC)
	rm -rf $(PS2DOCDIR)
	mkdir $(PS2DOCDIR)
	ruby $(DOCGEN) doc/api/*.txt
	cp -r $(DOCDIR)/ja/* $(COPYDOC)/ja/
	cp -r $(DOCDIR)/en/* $(COPYDOC)/en/
	rm -rf $(PS2DOCDIR)


archive : docs
	# Make package directory
	rm -rf $(PKGDIR)
	mkdir -p $(PKGDIR)
	mkdir -p $(PKGDIR)/ja $(PKGDIR)/en $(PKGDIR)/images
	mkdir -p $(PKGDIR)/ja/admin $(PKGDIR)/en/admin
	mkdir -p $(PKGDIR)/text
	cp $(DOCDIR)/*.css $(PKGDIR)/
	cp $(DOCDIR)/ja/*.html $(PKGDIR)/ja
	cp -r $(DOCDIR)/ja/man $(PKGDIR)/ja
	cp $(DOCDIR)/en/*.html $(PKGDIR)/en
	cp -r $(DOCDIR)/en/man $(PKGDIR)/en
	cp $(DOCDIR)/images/*.gif $(DOCDIR)/images/*.png $(PKGDIR)/images
	cp $(DOCDIR)/ja/admin/*.html $(DOCDIR)/ja/admin/*.gif $(DOCDIR)/ja/admin/*.png $(PKGDIR)/ja/admin/
	cp $(DOCDIR)/text/*.txt $(PKGDIR)/text/
	# Make archive
	zip -r -q $(PKGDIR).zip $(PKGDIR)
	rm -rf $(PKGDIR)


